name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:32
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        INSTALLROOT="$(mktemp -d)"
        dnf -y --installroot "${INSTALLROOT}" --releasever 32 install bash dnf man passwd shadow-utils sudo vim-minimal iproute iputils bind-utils tar openssh-server procps-ng
        find $INSTALLROOT
